### ISSUE TITLE
"Most Popular" posts not updating

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#734]
The Most Popular widget at the right side of the story page is stuck on old content.  Could be related to the resque job failing:

```
Class
 Job::MostViewed
Arguments
Exception
NoMethodError
Error
undefined method `each' for nil:NilClass
/scpr/scprv4_production/releases/20161228191723/app/jobs/job/most_viewed.rb:87:in `parse'
(eval):3:in `block in parse_with_newrelic_transaction_trace'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace'
(eval):2:in `parse_with_newrelic_transaction_trace'
/scpr/scprv4_production/releases/20161228191723/app/jobs/job/most_viewed.rb:26:in `perform'
```

AC:
- [x] Most Popular widget has updated content
- [x] Save credentials for reference later
- [x] Clean up old GA users
- [x] Email Becky to say we fixed it
- [x] Send an email telling people DON'T TOUCH ANYTHING
- [x] Write up instructions about how to get credentials if we ever need them again

**Comment by nakedsushi** [comment]
This is fixed for now. It was caused by the permission on Eric Richardson's GA account being restricted.  I unrestricted the permissions and we can go back to using the same client_id, token, and secret as before.

Will need to follow up with mpr so that it doesn't get restricted again, since getting a new client_id and token set up seems really confusing.  I'll also follow up with Eric to see how he provisioned those in the first place so that we can get it on an account that won't be automatically deleted.

**Comment by nakedsushi** [comment]
If in the event that the credentials get deleted, a developer will need to recreate them.  The easiest way is to use the [google-api-ruby-client](https://github.com/google/google-api-ruby-client), passing in the client_id and secret of the shared google account of the scpr developers.  Using the google-api-ruby-client seems to be the only way to reliably get a refresh token, which this background job needs.  When the auth URL is generated from that client, the developer will need to log in as the scpr shared dev account in google, go to that URL, and grant permission.  Granting permissions will redirect to the redirect_uri, with the authorization code in the URL. Use the authorization code to request the token, which should also come with the refresh token.  Update our key value store with the client_id, secret, token, and refresh_token, and hope that it works.
