### ISSUE TITLE
Bugfix: FetchMarketplaceArticles job

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#744]
The following job always fails and is cluttering up our resque failed queue. Either fix the job, or remove it from the queue:

AC:
- [x] Job is fixed or removed from being scheduled

```
Worker
sharedworker002:31927 on LOW_PRIORITY at 44 minutes ago Retry or Remove
Class
 Job::FetchMarketplaceArticles
Arguments
Exception
RuntimeError
Error
redirection forbidden: http://feeds.publicradio.org/public_feeds/marketplace-all-stories/rss/rss -> https://feeds.publicradio.org/public_feeds/marketplace-all-stories/rss/rss
/usr/lib/ruby/2.1.0/open-uri.rb:223:in `open_loop'
/usr/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/open_uri_redirections-0.2.1/lib/open-uri/redirections_patch.rb:55:in `open_uri'
/usr/lib/ruby/2.1.0/open-uri.rb:704:in `open'
/usr/lib/ruby/2.1.0/open-uri.rb:712:in `read'
/usr/lib/ruby/2.1.0/rss/parser.rb:103:in `normalize_rss'
/usr/lib/ruby/2.1.0/rss/parser.rb:89:in `initialize'
/usr/lib/ruby/2.1.0/rss/parser.rb:76:in `new'
/usr/lib/ruby/2.1.0/rss/parser.rb:76:in `parse'
/scpr/scprv4_production/releases/20170125000539/app/jobs/job/fetch_marketplace_articles.rb:12:in `perform'
```

**Comment by nakedsushi** [comment]
I think it's fixed. I'll keep an eye out on the failed jobs queue to verify.
