### ISSUE TITLE
Fix Job::SyncExternalPrograms

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#766]
AC:
- [ ] That job does not keep appearing in the Resque fail queue.

```
Job::SyncExternalPrograms
Arguments
--- rss
...
Exception
OpenSSL::SSL::SSLError
Error
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/usr/lib/ruby/2.1.0/net/http.rb:920:in `connect'
/usr/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
/usr/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/usr/lib/ruby/2.1.0/net/http.rb:920:in `connect'
/usr/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/usr/lib/ruby/2.1.0/net/http.rb:852:in `start'
/usr/lib/ruby/2.1.0/open-uri.rb:313:in `open_http'
/usr/lib/ruby/2.1.0/open-uri.rb:724:in `buffer_open'
/usr/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
/usr/lib/ruby/2.1.0/open-uri.rb:208:in `catch'
/usr/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
/usr/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/open_uri_redirections-0.2.1/lib/open-uri/redirections_patch.rb:55:in `open_uri'
/usr/lib/ruby/2.1.0/open-uri.rb:704:in `open'
/usr/lib/ruby/2.1.0/open-uri.rb:34:in `open'
/scpr/scprv4_production/releases/20170216214040/app/models/audio.rb:238:in `file'
/scpr/scprv4_production/releases/20170216214040/app/importers/rss_program_importer.rb:61:in `block in sync'
/scpr/scprv4_production/releases/20170216214040/app/importers/rss_program_importer.rb:41:in `each'
/scpr/scprv4_production/releases/20170216214040/app/importers/rss_program_importer.rb:41:in `sync'
(eval):3:in `block in sync_with_newrelic_transaction_trace'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace'
(eval):2:in `sync_with_newrelic_transaction_trace'
/scpr/scprv4_production/releases/20170216214040/app/importers/rss_program_importer.rb:14:in `sync'
/scpr/scprv4_production/releases/20170216214040/app/models/external_program.rb:117:in `sync'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:46:in `each'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:46:in `each'
/scpr/scprv4_production/releases/20170216214040/app/models/external_program.rb:92:in `sync'
/scpr/scprv4_production/releases/20170216214040/app/jobs/job/sync_external_programs.rb:12:in `perform'
```

**Comment by nakedsushi** [comment]
Released to prod. Going to keep an eye on this for the rest of this sprint to see if the error pops up in resque again, because it shouldn't.
