### ISSUE TITLE
Remove parse_push from breaking_news_alert.rb

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#854]
The hosted parse server is down, so we'll need to remove any code that still uses it. One place that uses it is in the breaking news alerts, which sends push notifications to people's devices.  If we don't need to go through Parse at all and OneSignal already does it, then we can just get rid of parse_push() completely.

AC:
- [ ] breaking_news_alert.rb#parse_push is removed or replaced and code calling that is modified as necessary

Error:
```
sharedworker002:11445 on MID_PRIORITY at 3 minutes ago
Class
 Job::SendMobileNotification
Arguments
--- BreakingNewsAlert
...

--- 2366
...
Exception
Parse::ParseProtocolError
Error
: HTTP Status 410 Body Parse.com has shutdown - https://parseplatform.github.io/
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/bundler/gems/parse-ruby-client-a4eb5618c816/lib/faraday/extended_parse_json.rb:25:in `process_response'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/faraday-0.8.9/lib/faraday/response.rb:63:in `on_complete'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/bundler/gems/parse-ruby-client-a4eb5618c816/lib/faraday/better_retry.rb:61:in `call'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/bundler/gems/parse-ruby-client-a4eb5618c816/lib/faraday/get_method_override.rb:30:in `call'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/faraday-0.8.9/lib/faraday/response.rb:8:in `call'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/faraday-0.8.9/lib/faraday/response/logger.rb:20:in `call'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/request/encode_json.rb:23:in `call'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/faraday-0.8.9/lib/faraday/connection.rb:253:in `run_request'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/faraday-0.8.9/lib/faraday/connection.rb:118:in `post'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/bundler/gems/parse-ruby-client-a4eb5618c816/lib/parse/client.rb:69:in `request'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/bundler/gems/parse-ruby-client-a4eb5618c816/lib/parse/push.rb:41:in `save'
/scpr/scprv4_production/releases/20170428184045/app/models/breaking_news_alert.rb:132:in `parse_push'
/scpr/scprv4_production/releases/20170428184045/app/models/breaking_news_alert.rb:115:in `publish_mobile_notification'
(eval):3:in `block in publish_mobile_notification_with_newrelic_transaction_trace'
/scpr/scprv4_production/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace'
(eval):2:in `publish_mobile_notification_with_newrelic_transaction_trace'
/scpr/scprv4_production/releases/20170428184045/app/jobs/job/send_mobile_notification.rb:10:in `perform'
```

**Comment by Ravenstine** [comment]
https://github.com/SCPR/SCPRv4/pull/860
